### ISSUE TITLE
Ошибка при склеивании чанков, аудиофайл создался. Загрузка всех 15-ти частей выполнилась.

### ISSUE THREAD

**Issue by NotTheD** [Alex-FIR-IT/Loader_for_webinar.ru#2]
Общая длительность вебинара: 5 часов 49 минут 19 секунд

(venv) D:\MIP>python main.py
Что необходимо сделать?
1. Выгрузить запись вебинара;
2. Запустить процесс слияние чанков;
3. Выгрузить несколько вебинаров, используя пакетную загрузку.
> 1
Вставьте, пожалуйста, ссылку на страницу с вебинаром:
> https://*ссылка*
Нужно ли будет запустить процесс слияния чанков? (да или нет)
> да
Количество видео-роликов: 15:
```
1) **тут были ссылки на видео в количестве 15 штук**
....
15)**тут были ссылки на видео в количестве 15 штук**
```
Загрузка началась!
https://*ссылка*: 100
1/15 выполнено!
https://*ссылка*: 100
2/15 выполнено!
https://*ссылка*: 100
3/15 выполнено!
https://*ссылка*: 100
4/15 выполнено!
https://*ссылка*: 100
5/15 выполнено!
https://*ссылка*: 100
6/15 выполнено!
https://*ссылка*: 100
7/15 выполнено!
https://*ссылка*: 100
8/15 выполнено!
https://*ссылка*: 100
9/15 выполнено!
https://*ссылка*: 100
10/15 выполнено!
https://*ссылка*: 100
11/15 выполнено!
https://*ссылка*: 100
12/15 выполнено!
https://*ссылка*: 100
13/15 выполнено!
https://*ссылка*: 100
14/15 выполнено!
https://*ссылка*: 100
15/15 выполнено!
Готово!
На скачивание затрачено 39.08607053756714 секунд
Невозможно объединить чанки в видео. Вместо этого будет произведен запуск слияния аудио.
MoviePy - Writing audio in D:\MIP\Общепсихологический_практикум_(пз)_2024-06-18_18_42_28\Общепсихологический_практикум_(пз)_2024-06-18_18_42_28.mp3
chunk:  45%|████████████████████████████████▌                                        | 154405/346251 [01:08<01:20, 2384.85it/s, now=None]Exception has been raised: index -100001 is out of bounds for axis 0 with size 0
Traceback (most recent call last):
  File "D:\MIP\scripts\files_merging.py", line 88, in merge_files
    videos = [VideoFileClip(filename=chunks_filepath) for chunks_filepath in chunks_filepaths]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\MIP\scripts\files_merging.py", line 88, in <listcomp>
    videos = [VideoFileClip(filename=chunks_filepath) for chunks_filepath in chunks_filepaths]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\MIP\venv\Lib\site-packages\moviepy\video\io\VideoFileClip.py", line 88, in __init__
    self.reader = FFMPEG_VideoReader(filename, pix_fmt=pix_fmt,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\MIP\venv\Lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 37, in __init__
    self.fps = infos['video_fps']
               ~~~~~^^^^^^^^^^^^^
KeyError: 'video_fps'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\MTS\venv\Lib\site-packages\moviepy\audio\io\readers.py", line 193, in get_frame
    result[in_time] = self.buffer[indices]
                      ~~~~~~~~~~~^^^^^^^^^
IndexError: index -100001 is out of bounds for axis 0 with size 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\MIP\main.py", line 173, in main
    merge_files(chunks_filepaths=webinar_info.get('chunks_filepaths'),
  File "D:\MIP\utils\decorators.py", line 41, in wrapper_2
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "D:\MIP\utils\decorators.py", line 18, in wrapper_2
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "D:\MIP\scripts\files_merging.py", line 110, in merge_files
    final_video.write_audiofile(filename=f'{filepath[:-1]}3')
  File "<decorator-gen-45>", line 2, in write_audiofile
  File "D:\MIP\venv\Lib\site-packages\moviepy\decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
           ^^^^^^^^^^^^^^^^
  File "D:\MIP\venv\Lib\site-packages\moviepy\audio\AudioClip.py", line 206, in write_audiofile
    return ffmpeg_audiowrite(self, filename, fps, nbytes, buffersize,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<decorator-gen-9>", line 2, in ffmpeg_audiowrite
  File "D:\MIP\venv\Lib\site-packages\moviepy\decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
           ^^^^^^^^^^^^^^^^
  File "D:\MIP\venv\Lib\site-packages\moviepy\audio\io\ffmpeg_audiowriter.py", line 166, in ffmpeg_audiowrite
    for chunk in clip.iter_chunks(chunksize=buffersize,
  File "D:\MIP\venv\Lib\site-packages\moviepy\audio\AudioClip.py", line 85, in iter_chunks
    yield self.to_soundarray(tt, nbytes=nbytes, quantize=quantize,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<decorator-gen-44>", line 2, in to_soundarray
  File "D:\MIP\venv\Lib\site-packages\moviepy\decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
           ^^^^^^^^^^^^^^^^
  File "D:\MIP\venv\Lib\site-packages\moviepy\audio\AudioClip.py", line 127, in to_soundarray
    snd_array = self.get_frame(tt)
                ^^^^^^^^^^^^^^^^^^
  File "<decorator-gen-11>", line 2, in get_frame
  File "D:\MIP\venv\Lib\site-packages\moviepy\decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
           ^^^^^^^^^^^^^^^^^^^
  File "D:\MIP\venv\Lib\site-packages\moviepy\Clip.py", line 93, in get_frame
    return self.make_frame(t)
           ^^^^^^^^^^^^^^^^^^
  File "D:\MIP\venv\Lib\site-packages\moviepy\audio\AudioClip.py", line 296, in make_frame
    sounds = [c.get_frame(t - c.start)*np.array([part]).T
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\MIP\venv\Lib\site-packages\moviepy\audio\AudioClip.py", line 296, in <listcomp>
    sounds = [c.get_frame(t - c.start)*np.array([part]).T
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "<decorator-gen-11>", line 2, in get_frame
  File "D:\MIP\venv\Lib\site-packages\moviepy\decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
           ^^^^^^^^^^^^^^^^^^^
  File "D:\MIP\venv\Lib\site-packages\moviepy\Clip.py", line 93, in get_frame
    return self.make_frame(t)
           ^^^^^^^^^^^^^^^^^^
  File "D:\MIP\venv\Lib\site-packages\moviepy\audio\io\AudioFileClip.py", line 77, in <lambda>
    self.make_frame = lambda t: self.reader.get_frame(t)
                                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\MIP\venv\Lib\site-packages\moviepy\audio\io\readers.py", line 205, in get_frame
    result[in_time] = self.buffer[indices]
                      ~~~~~~~~~~~^^^^^^^^^
IndexError: index -100001 is out of bounds for axis 0 with size 0

**Comment by Alex-FIR-IT** [comment]
Подозреваю, что проблема связана с тем, что скрипт пытается "склеить" mp3 файл и чанки mp4 файла воедино. Спасибо за предоставленную информацию, буду фиксить
